server:
  port: 8181
#  ssl:
#    key-store-password: uz44c1x1nos9
#    key-store: classpath:hechao.online.jks
#    key-store-type: jks

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.43.146:3306/springboot-vue?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: Hc020310..
  redis:
    port: 6379
    host: 101.34.43.146
    timeout: 1800000
    password: 123456
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 100MB


files:
  upload:
    path: E:/大学自学/Vue/springboot+vue/files/
    #path: /usr/local/app/springboot/files/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alipay:
  appId: 2021000122602047
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCfRbwi9BNNHl5BhgZBRd/V94xqg5efCcpQRGeX3N4cQ2pM+P1Nmpix6l37mBOaYe6Wfzd3+ijHqq7Sx9rI2eOpPoA44LzqbOjRf8R6eY9/81ffgQnUZF6nO90zYxawEZAZ+851x4WDuLqRpc/pXiFdFtiE79yXlBKOhUYLD3ZoJ/AGMxhFYwYB6i44QhXIIouMC9UxazNCokrFlNvTnzZn6Db0ED5xIsUHs3fB96tfIorqIyZMDmTAoawUp45TSuKO0pN+pBb20zGnzJXHpMXXy3mDZLkZNfTL9Gb8KgtisYI04XVPMxSAnP91dWBR2OWvjP4Mr+FC4mkqPHgZyWC9AgMBAAECggEAJQjrGVmVz13bXvMSK0VbKf646N+WdwWoxIdTa02RXBMU+bb/93aWQPCVT/ZpwIE7IEWOmVhS+TKoGh0cs41u0aDV4ePoKb6PWH+UKUJw6rij2zW/GmMIW2yhH9zPnrtGvbP+qwZs9lcTEuDyenpH2cSBLlA0BA8LTZaR1eqPhuI8ln1DvM6l37QD9rYPUDXUncmzsymc08g9h3AUkoUkfnCApC/CtnByCQEcoKHDxr7r3GWAKU7LntGvg0nw7/ts0JkzCEdRtP4UWvH4cAaulUpRVe2ssteX4lAXiwOc97ZMnFzgvbeKYFE6cfDKAcDRLZWJGj1y+6f15zGMNRoSBQKBgQDKpMetRRYhwJUyJsecXPZou40g4s3u/OmDCbmtWBCgl0WNVWMPN+lNhUUJFq45m7g2hFWzBXk2wi7PoA42dCEU/wqiUcPezCUtITlYfwa9xE1sb+p+v5eA9SAGaBwGmM0H5zTM6uORqDN8ryh9vfyxrHPGzYJhcK9krYmIrDtlawKBgQDJNYJtxZTUjxz7fCKH9khT37nt7hCxW8LN0gmUixWDur8RfkgBefti9O5P/5gw9gTezJ+HfPY6jJ0N/wPg8/AEj6nG/Ccg0+IFhDN2O3p9zdQeX/rdOXpBV8vDBMpNXyWrVB33Hme71HiVYpPYTeUxGWD4OH/Ph9S/uegubhq0dwKBgEXRiEqWpw1yAPWKjvO8w9lJ5VITUsiosvvG+gZTdUcfV4NejAbOSL/AzwxWmCiZElsWNUC8/gpz1RUMHFl+oXdOeCd87HNy+swVymBHQ9dWLybRWIXbFSQFUMdkT2Omed3jNznzI/0narXm05ifQNUmia1RWT6hSIzzjZNdZAmJAoGAWStxphxOHPVfrsQQuZiX7TPVPnCmzTMRXg2bWU1aN4rnamVAnAbnNa++fY2UcP5Wojak7HKg3Mm8QJunqGXzFNJmN11AKfg8zp0MAXXSjzZMrzlx/+CdIaA7GS5iSW/FTex1azL6Xe+HkQyi4NWEoQHSS68eVWapDl7hWtJI23kCgYA2P2tCzkU8+7JQWBBUZmA+dKVfj4+YCkr5kUGZadlirIjlKMg0ZIE/c4I6vmvvzaEGEW09z6VSuXfvN6PLA5qLX72iY30O2ATZiVqtKzjce78/LnRLp5IiH2cCicqRqxo+wwEvqmopzp2CtlJjEV47xe4gh5hCNsQ8IktySjRrzA==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmFWdtBByY+vmaRY4dra8WK/DQglQSL7aH0T4c0RttxlDuFYJG7trdVIj3OVjr0FWFv3MkcqBu3xWzYR/XP25JgbSFVSxdOF26VgCXXGvC3kIFFdUswaM3ISLmnXVQEMK56roa/BmUlP6R4TrU6UQ2jKC9kgdGNK1u8vrdb0/DpTby1K+vUl7qU75Th7JuSYWfi402hESNr1Mu8r3bzm40aEkwHs7FS6stIpNIQAbNWOStY3Fj1vqNXO/itMwi9/pvLbZ/7JfZzTzs0sRgyiL3zPTZdYh2F6o/BFMqkWrnB1vTYjLxw8DMC41PwZynZbJr4IDgKrxs6b4q5eAQ0PrvwIDAQAB
  notifyUrl: https://hechao.online:8181/alipay/notify




