server:
  port: 8181
#  ssl:
#    key-store-password: uz44c1x1nos9
#    key-store: classpath:hechao.online.jks
#    key-store-type: jks

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.43.146:3306/springboot-vue?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 1800000
    password: 123456
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 100MB


files:
  upload:
    path: E:/大学自学/Vue/springboot+vue/files/
    #path: /usr/local/app/springboot/files/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

alipay:
  appId: # 沙箱ID
  appPrivateKey: # 沙箱私有Key
  alipayPublicKey: # 沙箱公共Key
  notifyUrl: # 回调地址




